/* ____  ______________  ________________________  __________
 * \   \/   /      \   \/   /   __/   /      \   \/   /      \
 *  \______/___/\___\______/___/_____/___/\___\______/___/\___\
 *
 * Copyright 2023 Vavr, https://vavr.io
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.vavr.collection.euler;

import io.vavr.API;
import io.vavr.concurrent.Future;
import org.junit.Test;

import java.util.concurrent.TimeUnit;

import static org.assertj.core.api.Assertions.assertThat;

public class Euler44Test {

    /**
     * <strong>Problem 44 Pentagon numbers</strong>
     * <p>
     * Pentagonal numbers are generated by the formula, P<sub><i>n</i></sub>=<i>n</i>(3<i>n</i>−1)/2.
     * The first ten pentagonal numbers are: </p>
     * <p>
     * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
     * </p>
     * <p>
     * It can be seen that P<sub>4</sub> + P<sub>7</sub> = 22 + 70 = 92 = P<sub>8</sub>.
     * However, their difference, 70 − 22 = 48, is not pentagonal.
     * </p>
     * <p>
     * Find the pair of pentagonal numbers, P<sub><i>j</i></sub> and P<sub><i>k</i></sub>,
     * for which their sum and difference are pentagonal and D = |P<sub><i>k</i></sub> - P<sub><i>j</i></sub>|
     * is minimised; what is the value of D?
     * <p>
     * See also <a href="https://projecteuler.net/problem=44">projecteuler.net
     * problem 44</a>.
     */
    @Test
    public void shouldSolveProblem44() {
        // 创建一个Future对象，指定其执行的任务为minimalPentagonalDiff方法，并限制任务最多等待2秒
        final Future<Long> computation = API.Future(this::minimalPentagonalDiff)
                .await(2, TimeUnit.SECONDS);
        // 断言computation对象返回值为5482660，如果不是则抛出AssertionError异常
        assertThat(computation.getOrElse(-1L)).isEqualTo(5482660);
    }

    /**
     * 计算最小五边形数差值的私有方法
     *
     * @return 最小五边形数差值
     */
    private Long minimalPentagonalDiff() {
        // 使用 Utils.pentagonal() 方法生成一个无限流，表示所有五边形数
        return Utils.pentagonal().flatMap(sumPentagonal ->
                        // 使用 takeWhile 操作从五边形数流中提取出比 sumPentagonal 小的所有五边形数
                        Utils.pentagonal().takeWhile(pentagonal -> sumPentagonal.compareTo(pentagonal) > 0)
                                // filter 操作对于每个五边形数 pj，筛选出满足以下条件的五边形数
                                .filter(pj -> Utils.isPentagonal(sumPentagonal - pj) && Utils.isPentagonal(sumPentagonal - 2 * pj))
                                // map 操作将符合条件的五边形数 pj 映射为 sumPentagonal - 2 * pj，表示另一个满足条件的五边形数=差值
                                .map(pj -> sumPentagonal - 2 * pj))
                // 使用 head 操作获取流中第一个元素，即最小的五边形数差值
                .head();
    }
}
